name: Gradle Build
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        required: false
        default: '17'
      java_distribution:
        type: string
        required: false
        default: 'temurin'
      gradle_task:
        type: string
        required: false
        default: 'build'

jobs:
  gradle_build:
    name: Gradle Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '${{ inputs.java_version }}'
          distribution: '${{ inputs.java_distribution }}'

      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: '${{ inputs.gradle_task }} --scan'

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: '**/build/libs/*'
